services:
  app1:
    build: .
    container_name: goinfra-app1
    env_file:
      - .env
    environment:
      - PORT=8080
      - DB_HOST=${DB_HOST}
    ports:
      - "8080:8080"
    restart: always

  app2:
    build: .
    container_name: goinfra-app2
    env_file:
      - .env
    environment:
      - PORT=8080
      - DB_HOST=${DB_HOST}
    ports:
      - "8081:8080"
    restart: always
